print("----Início----")
print("Ir até o banheiro")
print("Pegar a pasta de dente com outra mão")
print("Abrir a pasta de dente com a outra mão")
print("Guardar a tampa")
print("Pegar a escova de dente com a outra mão")
print("Colocar a pasta na escova")
print("Guardar a pasta")
print("Abrir a boca com os dentes a mostra")
print("Passar a escova em movimentos circulares por todos os dentes")
print("Passar a escova da mesma forma na língua")
print("Cuspir")
print("Abrir a torneira")
print("Enxaguar a boca")
print("Colocar a escova debaixo da torneira")
print("Deixar 5 segundos")
print("Desligar a torneira")
print("Dar um pulo pra cima")
print("Sair do banheiro")
print("----Fim----")